# Generated by Django 2.1.8 on 2019-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='client',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
