# Generated by Django 2.1.8 on 2019-08-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_client_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='stripe_id',
        ),
    ]
