# Generated by Django 2.1.8 on 2019-08-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190805_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address_one', models.CharField(max_length=100)),
                ('address_two', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField(max_length=15)),
                ('stripe_id', models.CharField(blank=True, max_length=30)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Client')),
            ],
            options={
                'verbose_name_plural': 'subscribers',
            },
        ),
    ]
