# Generated by Django 2.1.8 on 2019-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_billingprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
