# Generated by Django 2.1.8 on 2019-08-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20190805_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingprofile',
            options={'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='plan',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='state',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
