# Generated by Django 2.1.8 on 2019-08-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20190812_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='plan',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
