# Generated by Django 2.1.11 on 2019-08-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_billingprofile_next_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='next_payment',
            new_name='paid_until',
        ),
    ]
