# Generated by Django 2.1.11 on 2019-08-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20190824_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='canceled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
