# Generated by Django 2.2.2 on 2019-06-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
