# Generated by Django 2.1.8 on 2019-07-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190620_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicles.Vehicle'),
        ),
    ]
