# Generated by Django 2.1.8 on 2019-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='gvw',
            field=models.IntegerField(blank=True, null=True, verbose_name='GVW'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='VIN'),
        ),
    ]
