# Generated by Django 2.2.24 on 2022-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_title_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='title_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Title #'),
        ),
    ]
